targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generator/{{file}}.g.dart'

      freezed:
        options:
          build_extensions:
            'lib/{{path}}/{{file}}.dart': 'lib/{{path}}/generator/{{file}}.freezed.dart'
          field_rename: snake
          explicit_to_json: true